FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app

EXPOSE 5011

CMD ["python", "-m", "flask", "--app", "cart_service/app.py", "run", "--host=0.0.0.0", "--port=5011"]
