version: "3.9"

services:

  auth-service:
    build: ./auth
    ports:
      - "5001:5001"
    volumes:
      - ./keys:/keys

  cert-service:
    build: ./cert
    ports:
      - "5002:5002"
    volumes:
      - ./keys:/keys

  validation-service:
    build: ./validation
    ports:
      - "5003:5003"
    volumes:
      - ./keys:/keys
    depends_on:
      - cert-service

  client-service:
    build: ./client
    ports:
      - "5004:5004"

  api-gateway:
    build: ./gateway
    ports:
      - "5005:5005"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml